name: 'CI Pipeline'
on:
  workflow_dispatch:

jobs:
  component-tests: 
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório.
        uses: actions/checkout@v4

      - name: Instalação do Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Instalação das dependências.
        run: npm install

      - name: Execução dos testes com Mock.
        run: npm run test-controller
      
      - name: Levantar a API.
        run: npm start &

      - name: Aguardar a API iniciar.
        run: sleep 5
      
      - name: Execução dos testes de API via HTTP.
        run: npm run test-external
      
      
